#!/bin/sh

serverip="192.168.1.99"
mountpoint="/apps"

for cmdline in `cat /proc/cmdline`
do
	case "$cmdline" in
	ip=*)
		serverip=`echo "$cmdline" | awk -F: '{print $2}'`
		;;
	esac
done

mount -t nfs -o nolock,tcp ${serverip}:${mountpoint} ${mountpoint}

if [ -x ${mountpoint}/etc/rc ]; then
  ${mountpoint}/etc/rc
fi

