#!/bin/sh

## application partition name
partname="rootfs"
## supported partition type list
parttype="squashfs jffs2"
## default mtd device
mtddev="/dev/mtdblock4"
## mount point
appmnt="/apps"

mtdnr=$(grep -E "\"${partname}\"" /proc/mtd \
      | grep -E -o '^mtd[0-9]{1,2}' \
      | cut -b 4-)

if [ x"$mtdnr" != "x" ]; then
  mtddev="/dev/mtdblock${mtdnr}"
fi

if ! [ -d ${appmnt} ]; then
  mkdir -p ${appmnt}
fi

## try to mount the apps partition
mount_ok=no
for t in ${parttype}; do
  if mount -t ${t} ${mtddev} ${appmnt} 2>/dev/null; then
    mount_ok=yes
    break
  fi
done

## run etc/rc script in this partition
init_ok=no
if [ -x ${appmnt}/etc/rc ]; then
  if ${appmnt}/etc/rc; then
    init_ok=yes
  fi
fi

if [ x"$mount_ok" != "xyes" -o x"$init_ok" != "xyes" ]; then
  echo -e "\033[31;1mENTER DOWNLOAD MODE\033[0m"
  ## light off or fast blink the system led
  if [ -f /apps/bin/sysled.sh ]; then
    /apps/bin/sysled.sh 0.2 &
  else
    himm 0x201c0020 0x8 > /dev/null
  fi
  ## startup network to default ipaddress
  ifconfig eth0 down
  ifconfig lo down
  ifconfig lo 127.0.0.1
  ifconfig eth0 192.168.1.217 netmask 255.255.255.0
  route add default gw 192.168.1.1
  ## start tftp server to upgrade the firmware
  /usr/bin/udpsvd -vE 0 69 /usr/bin/tftpd -c /var/cache/firmware &
  exit 1
else
  /apps/bin/sysled.sh 1 &
  exit 0
fi
