#!/bin/sh

evt=$1
fw_dir=$2
fw_file=$3

fw_path="${fw_dir}/${fw_file}"
lock_file="${fw_dir}/firmware-lock"

warn() {
  echo -e "\033[34;1mWARNING: $*\033[0m"
}

fatal() {
  echo -e "\033[31;1mFATAL: $*\033[0m"
}

## only process the event:
## w: Writable file was closed
## y: File was moved to Y
if ! [ x"${evt}" = "xw" -o x"${evt}" = "xy" ]; then
  exit 1
fi

## get file extension
file_ext=${fw_file##*.}
## firmware must be .bin or .fw extension
[ x"${file_ext}" != x"${fw_file}" ] || exit 1
[ x"${file_ext}" = "xbin" -o x"${file_ext}" = "xfw" ] || exit 1

if [ -f "${lock_file}" ]; then
  warn "Upgrade is processing"
  exit 1
fi

## delete lock_file on signal 0/1/2/3/6/9/15
cleanup() {
  rm -f ${lock_file}
  rm -f ${fw_path}
  rm -rf ${fw_dir}/files
}
trap "cleanup; exit 1" 0 1 2 3 6 9 15

touch $lock_file || exit 1

check_version() {
  if [ -z $1 ]; then
    warn "unknown new firmware version."
    return 1;
  fi

  old_ver=$(fw_version.sh)
  if [ -z $old_ver ]; then
    warn "can not get old firmware version."
    return 0;
  fi

  old_major=$(echo $old_ver | awk -F. '{print $1}')
  old_minor=$(echo $old_ver | awk -F. '{print $2}')
  old_revsion=$(echo $old_ver | awk -F. '{print $3}')

  new_major=$(echo $1 | awk -F. '{print $1}')
  new_minor=$(echo $1 | awk -F. '{print $2}')
  new_revsion=$(echo $1 | awk -F. '{print $3}')

  if [ -z $old_major -o \
       -z $old_minor -o \
       -z $old_revsion -o \
       -z $new_major -o \
       -z $new_minor -o \
       -z $new_revsion ]; then
    warn "bad format of version."
    return 1
  fi

  if [ $new_major -gt $old_major ]; then
    return 0
  fi
  if [ $new_minor -gt $old_minor ]; then
    return 0
  fi
  if [ $new_revsion -gt $old_revsion ]; then
    return 0
  fi

  return 1
}

## extract the firmware
echo 2 > ${lock_file}
echo -e "\033[1mExtracting the firmware...\033[0m"
new_ver=$(fw_decode -d ${fw_dir}/files ${fw_path} \
        | grep 'Version' \
        | awk '{print $2}')
if [ $? -ne 0 ]; then
  echo 0 > ${lock_file}
  fatal "Extract firmware failed"
  exit 1
fi

get_mtddev_from_name() {
  mtdnr=$(grep -E "\"$1\"" /proc/mtd \
        | grep -E -o '^mtd[0-9]{1,2}' \
        | cut -b 4-)
  if [ x"${mtdnr}" = "x" ]; then
    warn "partition '$f' does not exists, ignore."
    return 1;
  fi
  mtdcdev="/dev/mtd${mtdnr}"
  mtdbdev="/dev/mtdblock${mtdnr}"
  ## check the device
  if ! [ -c $mtdcdev -a -b $mtdbdev ]; then
    warn "MTD device ${mtdcdev}-${mtdbdev} does not exist"
    return 1;
  fi
  ## if filesystem is in-use, umount it first
  if grep "$mtdbdev" /proc/mounts; then
    local ignore=
    local mpoint=
    read ignore mpoint ignore << EOF
      $(grep -E "${mtdbdev}" /proc/mounts)
EOF
    if [ x"$mpoint" != "x" ]; then
      fuser -km $mpoint
      umount $mpoint
    fi
  fi
  return 0
}

## run pre-upgrade.sh
if [ -f ${fw_dir}/files/pre-upgrade.sh ]; then
  echo 3 > ${lock_file}
  cd ${fw_dir}/files
  . pre-upgrade.sh
  cd -
fi

if ! check_version $new_ver; then
  fatal "Check version failed"
  exit 1
fi

## program every partition
echo 3 > ${lock_file}
for f in $(ls ${fw_dir}/files); do
  if ! get_mtddev_from_name $f; then
    continue
  fi
  if [ -c ${mtdcdev} ]; then
    echo -e "\033[1mPrograming partition '${f}' to '${mtdcdev}'...\033[0m"
    if grep ${mtdbdev} /proc/mounts; then
      umount ${mtdbdev}
    fi
    flash_eraseall ${mtdcdev}
    flashcp -v ${fw_dir}/files/$f ${mtdcdev}
  else
    warn "partition '$f' is not a valid character device"
    continue
  fi
done

## run post-upgrade.sh
if [ -f ${fw_dir}/files/post-upgrade.sh ]; then
  echo 3 > ${lock_file}
  cd ${fw_dir}/files
  . post-upgrade.sh
  cd -
fi

fw_version.sh $new_ver
## program OK, reboot the system.
echo 4 > ${lock_file}
echo -e "\033[32;1mUpgrade complete, now rebooting system...\033[0m"
sleep 1
reboot

