#!/bin/sh

evt=$1
fw_dir=$2
evt_file=$3

act_file="upgrade-start"
fw_file="${fw_dir}/firmware-hi3518.bin"
lock_file="${fw_dir}/firmware-lock"

warn() {
  echo -e "\033[34;1mWARNING: $*\033[0m"
}

fatal() {
  echo -e "\033[31;1mFATAL: $*\033[0m"
}

## start when act_file is download
if ! [ x"${evt}" = "xw" \
    -a x"${evt_file}" = x"${act_file}" ];
then
  exit 0
fi

if [ -f "${lock_file}" ]; then
  warn "Upgrade is processing"
  exit 0
fi

## delete lock_file on signal 0/1/2/3/6/9/15
trap "rm -f ${lock_file}; exit 1" 0 1 2 3 6 9 15
touch $lock_file || exit 1

## check if the firmware file exists
if ! [ -f "${fw_file}" ]; then
  fatal "Firmware file not found"
  exit 1
fi

check_version() {
  if [ -z $1 ]; then
    warn "unknown new firmware version."
    return 1;
  fi

  old_ver=$(sqlite3 /data/configuration.sqlite3 \
          "select value from base_info where name=\"firmware\"")
  if [ -z $old_ver ]; then
    warn "can not get old firmware version."
    return 1;
  fi

  old_major=$(echo $old_ver | awk -F. '{print $1}')
  old_minor=$(echo $old_ver | awk -F. '{print $2}')
  old_revsion=$(echo $old_ver | awk -F. '{print $3}')

  new_major=$(echo $1 | awk -F. '{print $1}')
  new_minor=$(echo $1 | awk -F. '{print $2}')
  new_revsion=$(echo $1 | awk -F. '{print $3}')

  if [ -z $old_major -o \
       -z $old_minor -o \
       -z $old_revsion -o \
       -z $new_major -o \
       -z $new_minor -o \
       -z $new_revsion ]; then
    warn “bad format of version.”
    return 1
  fi

  if [ $new_major -gt $old_major ]; then
    return 0
  fi
  if [ $new_minor -gt $old_minor ]; then
    return 0
  fi
  if [ $new_revsion -gt $old_revsion ]; then
    return 0
  fi

  return 1
}

## extract the firmware
echo 2 > $lock_file
echo -e "\033[1mExtracting the firmware...\033[0m"
new_ver=$(fw_decode -d ${fw_dir}/files ${fw_file} \
        | grep 'Version' \
        | awk '{print $2}')
if [ $? -ne 0 ]; then
  echo 0 > $lock_file
  fatal "Extract firmware failed"
  exit 1
fi

if ! check_version $new_ver; then
  echo 0 > $lock_file
  fatal "Check version failed"
  exit 1
fi

get_mtddev_from_name() {
  mtdnr=$(grep -E "\"$1\"" /proc/mtd \
        | grep -E -o '^mtd[0-9]{1,2}' \
        | cut -b 4-)
  if [ x"${mtdnr}" = "x" ]; then
    warn "partition '$f' does not exists, ignore."
    return 1;
  fi
  mtdcdev="/dev/mtd${mtdnr}"
  mtdbdev="/dev/mtdblock${mtdnr}"
  ## check the device
  if ! [ -c $mtdcdev -a -b $mtdbdev ]; then
    warn "MTD device ${mtdcdev}-${mtdbdev} does not exist"
    return 1;
  fi
  ## if filesystem is in-use, umount it first
  if grep "$mtdbdev" /proc/mounts; then
    local ignore=
    local mpoint=
    read ignore mpoint ignore << EOF
      $(grep -E "${mtdbdev}" /proc/mounts)
EOF
    if [ x"$mpoint" != "x" ]; then
      fuser -km $mpoint
      umount $mpoint
    fi
  fi
  return 0
}

echo 3 > $lock_file
## program every partition
for f in $(ls ${fw_dir}/files); do
  if ! get_mtddev_from_name $f; then
    continue
  fi
  if [ -c ${mtdcdev} ]; then
    echo -e "\033[1mPrograming partition '${f}' to '${mtdcdev}'...\033[0m"
    flash_eraseall ${mtdcdev}
    flashcp -v ${fw_dir}/files/$f ${mtdcdev}
  else
    warn "partition '$f' is not a valid character device"
    continue
  fi
done

sqlite3 /data/configuration.sqlite3 "update base_info set value=\"$new_ver\" where name=\"firmware\""
echo 4 > $lock_file
## program OK, reboot the system.
echo -e "\033[32;1mUpgrade complete, now rebooting system...\033[0m"
sleep 1
reboot

